### ISSUE TITLE
freq: show video and controls for uploaded files

### ISSUE THREAD

**Issue by Tragen** [Shadowsith/mattermost-plugin-videourl#5]
Currently when I upload an mp4, I only get an icon where I can click on and view the video.
Could you add the option to directly show the video with the video player controls?
Like in Discord or Slack?

**Comment by Shadowsith** [comment]
Hi @Tragen , you can use my other plugin: https://github.com/Shadowsith/mattermost-plugin-videofile for that.

I have currently split these features between two plugins.
I have also written one plugin each for audio urls and audio files.

**Comment by Tragen** [comment]
Amazing, I will try it.
